### ISSUE TITLE
Could you please make it Command line arguments based.

### ISSUE THREAD

**Issue by bhunterex** [HexShad0w/Sh1dowQLI#1]
If you make it command line argument then it will be better for us. As like Picture.
![1-url](https://github.com/user-attachments/assets/2e7741aa-ffc1-4932-ad32-4a72f9bc4904)
![2-file](https://github.com/user-attachments/assets/6df28bb8-794b-421a-88ea-bd356c3e4d65)

**Comment by HexShad0w** [comment]
Hello,

I will do that

Thanks,
hexsh1dow

**Comment by bhunterex** [comment]
I'm waiting for that. Thanks

**Comment by HexShad0w** [comment]
Updated

Thanks for the idea ✊️

hexsh1dow

**Comment by bhunterex** [comment]
You're welcome
